# Generated by Django 5.1.2 on 2024-12-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='nss',
            field=models.CharField(max_length=100),
        ),
    ]
