# Generated by Django 5.0.2 on 2024-12-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierpatient',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='qr_code/'),
        ),
    ]
