# Generated by Django 5.1.2 on 2024-12-11 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonnance',
            name='medicaments',
        ),
        migrations.RemoveField(
            model_name='soininfermiermedicament',
            name='medicament',
        ),
        migrations.RemoveField(
            model_name='soininfermiermedicament',
            name='soin_infirmier',
        ),
        migrations.RemoveField(
            model_name='dossierpatient',
            name='examen_bio',
        ),
        migrations.RemoveField(
            model_name='dossierpatient',
            name='examen_radio',
        ),
        migrations.RemoveField(
            model_name='dossierpatient',
            name='soin_infirmier',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='qr',
        ),
        migrations.RemoveField(
            model_name='soininfermier',
            name='medicament_administré',
        ),
        migrations.AddField(
            model_name='dossierpatient',
            name='qr',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicament',
            name='ordonnance',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='accounts.ordonnance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicament',
            name='soin',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='accounts.soininfermier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soininfermier',
            name='dossier',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='soins_infirmiers', to='accounts.dossierpatient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificat',
            name='medecin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificats', to='accounts.technician'),
        ),
        migrations.AlterField(
            model_name='examenbiologique',
            name='technicien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_biologiques', to='accounts.technician'),
        ),
        migrations.AlterField(
            model_name='examenradiologique',
            name='technicien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_radiologiques', to='accounts.technician'),
        ),
        migrations.AlterField(
            model_name='soininfermier',
            name='infirmier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins_infirmiers', to='accounts.technician'),
        ),
        migrations.DeleteModel(
            name='OrdonnanceMedicament',
        ),
        migrations.DeleteModel(
            name='SoinInfermierMedicament',
        ),
    ]
