# Generated by Django 5.1.2 on 2024-12-13 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_ordonnance_medicaments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='ordonnance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='accounts.ordonnance'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='ordonnance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='accounts.ordonnance'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='soin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='accounts.soininfermier'),
        ),
    ]
