# Generated by Django 5.1.2 on 2024-12-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_patient_nss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierpatient',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='qr_code/'),
        ),
    ]
