# Generated by Django 5.1.2 on 2024-12-28 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_dossierpatient_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenbiologique',
            name='laborantin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_biologiques_labo', to='accounts.technician'),
        ),
        migrations.AddField(
            model_name='examenradiologique',
            name='radiologue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_radiologiques_radio', to='accounts.technician'),
        ),
        migrations.CreateModel(
            name='RadiologyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='radiology_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.examenradiologique')),
            ],
        ),
    ]
