# Generated by Django 5.1.2 on 2024-12-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_consultation_ordonnance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='diagnostic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examenbiologique',
            name='terminaison',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='examenradiologique',
            name='compte_rendu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examenradiologique',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='radiology_images/'),
        ),
        migrations.AlterField(
            model_name='examenradiologique',
            name='terminaison',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resultatexamen',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soininfermier',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technician',
            name='outils',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technician',
            name='specialite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
