# Generated by Django 5.1.2 on 2024-12-28 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_examenbiologique_laborantin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radiologyimage',
            old_name='examen',
            new_name='examen_radiologique',
        ),
    ]
