# Generated by Django 5.0.2 on 2024-12-18 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_admin'),
        ('accounts', '0004_alter_consultation_diagnostic_and_more'),
    ]

    operations = [
    ]
