# Generated by Django 5.1.2 on 2024-12-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_resume_alter_consultation_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='diagnostic',
        ),
        migrations.RemoveField(
            model_name='examenbiologique',
            name='terminaison',
        ),
        migrations.RemoveField(
            model_name='examenradiologique',
            name='terminaison',
        ),
        migrations.AddField(
            model_name='consultation',
            name='diagnosticStatut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examenbiologique',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examenradiologique',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='resultatexamen',
            unique_together={('parametre', 'examen_biologique')},
        ),
    ]
