# Generated by Django 5.1.2 on 2024-12-28 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_examen_radiologyimage_examen_radiologique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examenradiologique',
            name='image',
        ),
    ]
