# Generated by Django 5.0.2 on 2024-12-22 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20241218_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic', models.TextField(blank=True, null=True)),
                ('symptomes', models.TextField(blank=True, null=True)),
                ('mesures_prises', models.TextField(blank=True, null=True)),
                ('date_prochaine_consultation', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='diagnostic',
        ),
        migrations.RemoveField(
            model_name='examenbiologique',
            name='terminaison',
        ),
        migrations.RemoveField(
            model_name='examenradiologique',
            name='terminaison',
        ),
        migrations.AddField(
            model_name='consultation',
            name='diagnosticStatut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examenbiologique',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examenradiologique',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='email@example.com', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('technicien', 'Technicien'), ('patient', 'Patient'), ('administratif', 'Administratif')], default='admin', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='resultatexamen',
            unique_together={('parametre', 'examen_biologique')},
        ),
        migrations.CreateModel(
            name='Administratif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administratif', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='consultation',
            name='resume',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='accounts.resume'),
        ),
    ]
