# Generated by Django 5.1.2 on 2024-12-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_examenradiologique_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologyimage',
            name='titre',
            field=models.TextField(blank=True, null=True),
        ),
    ]
