# Generated by Django 5.0.2 on 2024-12-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_resume_remove_consultation_diagnostic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='role',
            field=models.CharField(choices=[('medecin', 'medecin'), ('infermier', 'infermier'), ('laborantin', 'laborantin')], max_length=50),
        ),
    ]
