# Generated by Django 5.1.2 on 2025-01-01 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_radiologyimage_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiologyimage',
            name='examen_radiologique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='accounts.examenradiologique'),
        ),
    ]
