# Generated by Django 5.0.2 on 2024-12-30 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_dossierpatient_qr'),
        ('accounts', '0007_radiologyimage_titre'),
    ]

    operations = [
    ]
