# Generated by Django 5.1.2 on 2025-01-01 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_radiologyimage_examen_radiologique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiologyimage',
            name='examen_radiologique',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.examenradiologique'),
            preserve_default=False,
        ),
    ]
