# Generated by Django 5.1.2 on 2024-12-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_role_administratif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='duree',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='frequence',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
