<<<<<<< HEAD
# Generated by Django 5.1.2 on 2024-12-23 03:58
=======
# Generated by Django 5.1.2 on 2024-12-23 02:53
>>>>>>> 74bc5105eeeb1dbf8cebaf26653ec4bcff53afa0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_medicament_duree_alter_medicament_frequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='role',
            field=models.CharField(choices=[('medecin', 'medecin'), ('infermier', 'infermier'), ('laborantin', 'laborantin'), ('radiologue', 'radiologue')], max_length=50),
        ),
    ]
