# Generated by Django 5.1.2 on 2025-01-01 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merge_20241230_2214'),
        ('accounts', '0009_alter_radiologyimage_examen_radiologique'),
    ]

    operations = [
    ]
