# Generated by Django 5.1.2 on 2024-12-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_technician_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='soininfermier',
            name='heure',
            field=models.TimeField(default='15:00'),
        ),
    ]
